
base_model: /model/Llama-3.2-1B

#model_type: LlamaForCausalLM

model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer


load_in_8bit: true
load_in_4bit: false
strict: false

chat_template: llama3

#datasets:
  #- path: "/datasets/ubiquitous_bash_finetuning-continueText.jsonl"
    #type: "completion"

#datasets:
  #- path: "/datasets/ubiquitous_bash_finetuning-promptResponse.jsonl"
    #type: chat_template
    #field_messages: messages
    #message_property_mappings:
      #role: role
      #content: content
    #roles:
      #system:
        #- system
      #user:
        #- user
      #assistant:
        #- assistant

datasets:
  - path: fozziethebeat/alpaca_messages_2k_test
    type: chat_template
    field_messages: messages
    message_property_mappings:
      role: role
      content: content
    roles:
      user:
        - user
      assistant:
        - assistant


dataset_prepared_path:

#val_set_size: 0.05
val_set_size: 0.00

output_dir: /outputs/experiment-ubiquitous_bash/lora-out

sequence_len: 4096
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: true

adapter: lora
lora_model_dir:
lora_r: 16
lora_alpha: 4
lora_dropout: 0.05
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_8bit
lr_scheduler: cosine
#learning_rate: 0.0002
#learning_rate: 0.0001
learning_rate: 0.00003

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
s2_attention:

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_steps: 10
evals_per_epoch: 4
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: "<|end_of_text|>"
