
# ATTRIBUTION-AI: May inherit code written for other CI YAML scripts by ChatGPT o1 .
# ATTRIBUTION-AI: DeepSeek R1 14b 2025-02-07

name: test-patch


# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none



on:
  push:
  workflow_dispatch:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    - cron: '1 1 * * *'

jobs:
  test-patch:
    runs-on: ubuntu-latest
    steps:
      - name: _getCore_ub
        shell: bash
        timeout-minutes: 90
        run: |
          mkdir -p ~/core/infrastructure
          cd ~/core/infrastructure
          git clone --depth 1 --recursive https://github.com/mirage335-colossus/ubiquitous_bash.git
          cd ubiquitous_bash
          ./_setupUbiquitous.bat
      - uses: actions/checkout@v3
      - name: Download the YAML file
        run: |
          cd ./_import/etc--searxng
          curl --output settings.yml 'https://raw.githubusercontent.com/searxng/searxng/refs/heads/master/searx/settings.yml'
      - name: Apply the patch
        run: |
          cd ./_import/etc--searxng
          #patch -p1 settings.yml < settings.yml.patch
          yes | patch -p1 settings.yml settings.yml.patch && exit 0
          ~/core/infrastructure/ubiquitous_bash/ubiquitous_bash.sh _messagePlain_bad 'bad: FAIL: patch'
          cat settings.yml.patch
          ~/core/infrastructure/ubiquitous_bash/ubiquitous_bash.sh _messagePlain_request 'Please download settings.yml, patch, change any unpatched regions to match the changes shown in the patch file, then SPECIFICALLY use the git diff command to create a new patch between the upstream original settings.yml and desired settings.yml . Resulting patch may itself be compared to previous patch with diff , git diff , etc .'
          ~/core/infrastructure/ubiquitous_bash/ubiquitous_bash.sh _messageFAIL

      - name: Check if patch still applies correctly
        run: |
          cd ./_import/etc--searxng
          [[ -e ./_import/etc--searxng/settings.yml.rej ]] && exit 1
          true




